### ISSUE TITLE
How do i build

### ISSUE THREAD

**Issue by sonicdemo** [CalcuIator/RSDK-Animation-Editor#1]
I launched the exe and nothing happened, how do i build this!

**Comment by CalcuIator** [comment]
Just compile it, you can't directly launch the exe, it has to be launched from the start menu since it's a packaged app

**Comment by sonicdemo** [comment]
It got built, it wasn't packed

**Comment by sonicdemo** [comment]
Maybe because an "RSDK.AnimationEditor_TemporaryKey.pfx" certificate wasn't found.

**Comment by CalcuIator** [comment]
![image](https://user-images.githubusercontent.com/104047615/218327628-30bc4ce4-54d1-481b-843f-430c6da619ce.png)
Open Package,appxmanifest, go to the packaging section there will be a choose certificate button on the right

Click on it and then press create

After the new certificate is there, compile it

After it's compiled, it'll be in the start menu
![image](https://user-images.githubusercontent.com/104047615/218327843-e0a066f9-1190-41e6-ac23-37642d6804da.png)

**Comment by sonicdemo** [comment]
![Zrzut ekranu (1813)](https://user-images.githubusercontent.com/121387979/218332790-9803096f-d051-4e0a-aff3-796685b9c228.png) I get this, in which way do i open this?

**Comment by CalcuIator** [comment]
Opening the .sln, and then double clicking Package.appxmanifest should show the GUI

**Comment by sonicdemo** [comment]
I did just that lmao, and shows me code for some reason

**Comment by CalcuIator** [comment]
Not sure why, I'll just push an already built version some time later

**Comment by sonicdemo** [comment]
That would be great! Anyways, closing the issue.

**Comment by CalcuIator** [comment]
https://github.com/CalcuIator/RSDK-Animation-Editor/releases/tag/main

**Comment by sonicdemo** [comment]
Application installer that does not support the package. Ask the developer for the new application package Microsoft.WindowsAppRuntime.1.3-experimental1. I got this (i translated it with google translate so mistakes might be here)

**Comment by CalcuIator** [comment]
I forgot to include the dependencies, I'll update the release later

**Comment by CalcuIator** [comment]
Should be fine now

**Comment by sonicdemo** [comment]
![Zrzut ekranu (1829)](https://user-images.githubusercontent.com/121387979/218578823-3911c328-2b98-487a-898a-d2f8a6ebfcb8.png)
![Zrzut ekranu (1830)](https://user-images.githubusercontent.com/121387979/218578888-0890fac1-34bd-4112-8ebf-e34a751a4eb7.png)
Now there are issues in the program itself. Texture manager does work fine though. The frames just don't display. Should we move this to another thread?

**Comment by CalcuIator** [comment]
It's far from done, I about basically every issue

**Comment by CalcuIator** [comment]
I know about*

**Comment by sonicdemo** [comment]
Well, then, it will take a while to be compatible on my pc.

**Comment by sonicdemo** [comment]
It's broken even on your pc LMAO

**Comment by CalcuIator** [comment]
It's not broken, just unimplemented
